apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: duck-api
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: duck-api
            port:
              number: {{ .Values.port }}
        path: /
        pathType: Prefix
