apiVersion: v1
kind: Service
metadata:
  name: duck-api
  namespace: {{ .Values.namespace }}
  labels:
    service: duck-api
spec:
  selector:
    service: duck-api
  ports:
  - name: http
    port: {{ .Values.port }}
    targetPort: {{ .Values.targetPort }}
    protocol: TCP
