image:
  app:
    url: 465700395685.dkr.ecr.eu-west-1.amazonaws.com/duck/api
    tag: latest
    pullPolicy: IfNotPresent
    pullSecret: aws-registry
  filebeat:
    url: elastic/filebeat:7.17.0
    pullPolicy: IfNotPresent

port: 4000
targetPort: 4000

logPath: /app/logs

replicas: 1

resources:
  limits:
    cpu: 0.1
    memory: 128M
  requests:
    cpu: 0.1
    memory: 128M
